[features]
seeds = false
skip-lint = false
[programs.localnet]
read_write = "A8aYf8PvbhgwC3mSA8RPKZwXuLnzbkoBRTDi5cx39P3p"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/renzo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
